# Generated by Django 6.0.5 on 2026-05-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=11),
        ),
    ]
