# Generated by Django 6.0.5 on 2026-05-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
