# Generated by Django 6.0.5 on 2026-05-22 00:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_remove_category_updated_at_category_icon_class_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shop_name', models.TextField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense')], max_length=3)),
                ('transaction_date', models.DateField(default=datetime.datetime(2026, 5, 22, 0, 54, 40, 226372, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateField(auto_now=True)),
                ('account_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_admin', to=settings.AUTH_USER_MODEL)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txn_user', to=settings.AUTH_USER_MODEL)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
        ),
    ]
