# Generated by Django 6.0.5 on 2026-05-22 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='shop_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 22, 7, 2, 5, 96618, tzinfo=datetime.timezone.utc)),
        ),
    ]
