# Generated by Django 6.0.5 on 2026-05-22 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_shop_name_transaction_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='title',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 22, 7, 4, 24, 115382, tzinfo=datetime.timezone.utc)),
        ),
    ]
