# Generated by Django 6.0.5 on 2026-05-23 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_title_transaction_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 23, 3, 52, 7, 823144, tzinfo=datetime.timezone.utc)),
        ),
    ]
