# Generated by Django 6.0.5 on 2026-05-24 11:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_account_admin'),
        ('transaction', '0004_rename_category_name_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='account.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 24, 11, 17, 45, 210816, tzinfo=datetime.timezone.utc)),
        ),
    ]
