# Generated by Django 6.0.5 on 2026-05-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_updated_at_category_icon_class_and_more'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['purchased', 'id']},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_lists', to='category.category'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
