# Generated by Django 6.0.5 on 2026-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_alter_shoppingitem_options_shoppingitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
