# Generated by Django 6.0.5 on 2026-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_shoppinglist_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
