# Generated by Django 6.0.5 on 2026-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppingitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
