# Generated by Django 6.0.5 on 2026-05-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_shoppinglist_total_spent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
